### ISSUE TITLE
Writing the Introduction

### ISSUE THREAD

**Issue by essepuntato** [open-sci/invalid-dois-and-citations-article#1]

**Comment by essepuntato** [comment]
HI @Alessia438,

I've assigned this section to you. @sntcristian and @arcangelo7, please be ready to provide any feedback if Alessia will need it, OK?

**Comment by essepuntato** [comment]
Please confirm if this issue is closed.

**Comment by Alessia438** [comment]
Yes, I confirm that the issue is closed.
