### ISSUE TITLE
Revise article and comments

### ISSUE THREAD

**Issue by essepuntato** [open-sci/invalid-dois-and-citations-article#5]
The article has been revised and several comments have been provided and need to be addressed, in order to clarify certain aspects better.

Please, use the suggesting mode for editing the current version of the article, to allow understanding easily what you have modified.

As an additional note, the deadlines have been modified for one week so as to enable us to address all these comments properly. The new deadline for this activity is **October 10**.

**Comment by arcangelo7** [comment]
The upcoming deadline for submitting the thesis did not allow some of us to meet the deadline for revising this article. By mutual agreement, we would like to ask for an additional two weeks to address all comments, moving the deadline to October 24.

**Comment by essepuntato** [comment]
OK, great! Just modified all the deadlines specified in the milestones to reflect this change.

**Comment by arcangelo7** [comment]
All the comments have been addressed.
